### ISSUE TITLE
AUR package bannertool-git does not build

### ISSUE THREAD

**Issue by Ketchup901** [phijor/ctroller#1]
Accidentally pressed enter, writing this now.

So the AUR package for bannertool does not build, and since it's a dependency for ctroller-git, it will not build, even if you have bannertool installed.

**Comment by phijor** [comment]
I just reinstalled bannertool-git and it builds fine for me. You should contact the maintainer of the package if the issue persists.

But I see that installing the complete 3DS dev-toolchain just to install binaries that can be precompiled is kind of overkill. I just made [ctroller-bin](https://aur.archlinux.org/packages/ctroller-bin/), which downloads the 3DS binaries from the github releases and builds the server from the matching tag/release.

**Comment by Ketchup901** [comment]
That's a good call, thanks for doing that.
