### ISSUE TITLE
For any other linux version?

### ISSUE THREAD

**Issue by the100guy** [phijor/ctroller#2]
I'm not running Arch and was hoping to get this running on my Raspberry Pi Retropie setup, however, that runs on Debian. I'm not sure if its even possible for me to run an Arch thing on Debian (probably not though), so would you consider making it for other linux versions? 
Thanks

**Comment by phijor** [comment]
Oh, I should probably make that more clear in the readme:

ctroller should compile fine on all Linux-distros, I just happen to have made an package for Arch ready to be installed.

Running `make` in the repo should already give you a working executable.

I will update the readme in this regard. 

If you have further questions just go ahead and ask me.

**Comment by the100guy** [comment]
running `make` sort of works, but its giving me errors and such. I'll just c/p what it gives me and I hope you can help me out here.

pi@retropie:~/RetroPie/ctroller-master/linux $ make
Creating directories
Beginning release build
Compiling: src/main.c -> build/release/main.o
src/main.c: In function ‘main’:
src/main.c:134:12: warning: missing initializer for field ‘version’ of ‘struct h                          idinfo’ [-Wmissing-field-initializers]
     struct hidinfo hid = {};
            ^
In file included from include/ctroller.h:6:0,
                 from src/main.c:31:
include/hid.h:69:14: note: ‘version’ declared here
     uint16_t version;
              ^
In file included from src/main.c:31:0:
include/ctroller.h:18:37: error: ‘VERSION_MAJOR’ undeclared (first use in this f                          unction)
 #define CTROLLER_VERSION MAKEBCDVER(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH                          )
                                     ^
include/ctroller.h:12:7: note: in definition of macro ‘MAKEBCDVER’
     ((major & 0xf) << 8 | (minor & 0xf) << 4 | (patch & 0xf))
       ^
src/main.c:152:36: note: in expansion of macro ‘CTROLLER_VERSION’
                 if (hid.version != CTROLLER_VERSION) {
                                    ^
include/ctroller.h:18:37: note: each undeclared identifier is reported only once                           for each function it appears in
 #define CTROLLER_VERSION MAKEBCDVER(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH                          )
                                     ^
include/ctroller.h:12:7: note: in definition of macro ‘MAKEBCDVER’
     ((major & 0xf) << 8 | (minor & 0xf) << 4 | (patch & 0xf))
       ^
src/main.c:152:36: note: in expansion of macro ‘CTROLLER_VERSION’
                 if (hid.version != CTROLLER_VERSION) {
                                    ^
include/ctroller.h:18:52: error: ‘VERSION_MINOR’ undeclared (first use in this f                          unction)
 #define CTROLLER_VERSION MAKEBCDVER(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH                          )
                                                    ^
include/ctroller.h:12:28: note: in definition of macro ‘MAKEBCDVER’
     ((major & 0xf) << 8 | (minor & 0xf) << 4 | (patch & 0xf))
                            ^
src/main.c:152:36: note: in expansion of macro ‘CTROLLER_VERSION’
                 if (hid.version != CTROLLER_VERSION) {
                                    ^
include/ctroller.h:18:67: error: ‘VERSION_PATCH’ undeclared (first use in this f                          unction)
 #define CTROLLER_VERSION MAKEBCDVER(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH                          )
                                                                   ^
include/ctroller.h:12:49: note: in definition of macro ‘MAKEBCDVER’
     ((major & 0xf) << 8 | (minor & 0xf) << 4 | (patch & 0xf))
                                                 ^
src/main.c:152:36: note: in expansion of macro ‘CTROLLER_VERSION’
                 if (hid.version != CTROLLER_VERSION) {
                                    ^
Makefile:194: recipe for target 'build/release/main.o' failed
make[1]: *** [build/release/main.o] Error 1
Makefile:124: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by phijor** [comment]
I figured out what your issue is. Did you download the repository as a zip file? If so, ctroller does not know what version it is building. The build process tries to figure out the version from the git-repository itself, which is missing from the zip file.

To be able to compile ctroller, you need to install [git](https://git-scm.com/) with your package manager and clone the repository:

```
$ git clone https://github.com/phijor/ctroller.git
```

Does that help you?

**Comment by the100guy** [comment]
yes it does, thanks so much for the help!

**Comment by phijor** [comment]
Glad I could help you :) I hope ctroller is useful to you.

If you have any suggestions/feature requests/questions/... just go ahead and post an issue.
