### ISSUE TITLE
Screen rotation changes constantly

### ISSUE THREAD

**Issue by Pablare** [phijor/ctroller#5]
As soon as a connection is made between the linux app and the 3ds the screen orientation starts rapidly changing in Gnome.
I have build the linux app from source but installed the 0.4 CIA.

**Comment by phijor** [comment]
`ctroller` provides your system with input devices for both the 3DS' accelerometer and gyroscope. So I guess GNOME reads their data and uses that to figure out the current screen orientation.

As a temporary workaround, could you try locking the screen orientation in GNOME?

If it is indeed those devices causing GNOME to think your device changed orientation, I think I'll need to add a program option to selectively disable them.

**Comment by phijor** [comment]
For reference, here is someone having a similar issue:

https://unix.stackexchange.com/questions/330194/stop-fedora-gnome-auto-rotate-screen-when-shake-laptop

Here, the suggested fix was to disable their hard drive accelerometer.

**Comment by Pablare** [comment]
Yes locking the screen rotation indeed solves this problem. Also it seems you are right about the accelerometer being the cause, since the Orientation doesn't chance with the 3ds lying flat on the table.




As an aside note, this is really awesome and you are so cool and thank you for writing this. The latency is low enough to play super Mario world which I didn't expect. This saves me 30 bucks for a Bluetooth controller for the time being.

**Comment by phijor** [comment]
Ah, thank you for confirming the issue :+1:

I'm grateful that you enjoy `ctroller`. I guess that should be motivation for me to continue work on this app!
